### PR TITLE
fix(io): avoid error when loading a zip in a zip

### PR DESCRIPTION
**Pull request by PaulHax**
With nested zip files, the original zip file would get mixed in with the extracted files, resulting in an Error: cannot find reader for .zip

Test file with nested zip.
[zip-in-zip.zip](https://github.com/Kitware/VolView/files/11182269/zip-in-zip.zip)

Also, remove unused and buggy makeZip()

### CODE REVIEW

**Comment by floryst** [comment]
I'm seeing an error when loading the same session file twice. Repro steps:
1. Load the zip-in-zip.zip dataset
2. Paint in any view
3. Save the session
4. Without reloading, try to load the saved session file (I just did drag-n-drop)

image

**Comment by PaulHax** [comment]
> I'm seeing an error when loading the same session file twice.

Hmm.  Seems loading a session.volview.zip containing a dataset that's already loaded has been a problem since at least 80caf04e654ebe4a3e921f962d6768398a6da6c7

**Comment by floryst** [comment]
Looks like it's actually just any zip file, painting not needed. Repro'd on the stable branch.

1. Load a zip file
2. Save the session
3. Load the session without refreshing the page

**Comment by floryst** [comment]
This PR looks good, so I'll open an issue for this other bug.

**Pull request merged**
