### PR TITLE
feat(ControlStrip): Moved menu button to ControlStrip

### PR DESCRIPTION
**Pull request by lchauvin**
Related to https://github.com/Kitware/VolView/issues/604

### CODE REVIEW

**Comment by floryst** [comment]
@PaulHax what do you think of the placement? The alternative would be to remove the `v-if="mobile"` and have the button showing on the left of the logo.

**Comment by PaulHax** [comment]
Left of logo would look good to.  Strangely I don't have a strong opinion =)  Just a slight unease about the "connection" between the button and the drawer, but no obvious solution.  Overall I think this is a nice upgrade.

**Comment by lchauvin** [comment]
I decided to put it there, because initially it was left of the logo, but I didn't see it immediately. I thought putting on the menu, you can't miss it.

**Comment by floryst** [comment]
Try reverting your changes and drop the `v-if="mobile"` attr to show the menu button unconditionally and let me know what you think. I agree that there is some tenuous connection with the positioning of the menu button in the control strip, and it might work better to the left of the logo. Would be good to get your opinion on it.

**Comment by lchauvin** [comment]
I could put it next to the logo if you think it's better. However, like I said, it was initially there, but it wasn't directly clear to me what was this button for, maybe because of the logo right next to it, I'm not sure. I felt like it was gonna open another dropdown menu or something like that.

**Comment by floryst** [comment]
I think this is consistent with how some existing designs operate. The material design website and vuetify's website both use the triple bar icon around the logo to toggle the sidebar visibility on smaller screens. In this case, we are just enabling that functionality regardless of screen size.

**Pull request merged**
