### PR TITLE
Welcome page loading indicator

### LINKED ISSUE #495: Show "Loading..." on welcome screen when loading sample, URL, or local data
Will correctly inform user that loading is still happening after thumbnail appears and in other contexts.

### PR DESCRIPTION
**Pull request by floryst**
- Refactors out the welcome page to a separate component
- Adds a loading indicator to the welcome page

Closes #495 and partially addresses #365.

### CODE REVIEW

**Comment by aylward** [comment]
Nice!

Works great for local data.

Can we also have the Loading message appear when loading data via URL, such as
https://deploy-preview-497--volview-dev.netlify.app/?urls=[https://data.kitware.com/api/v1/file/6347145311dab81428208e21/download]

s

**Comment by aylward** [comment]
Maybe also while loading sample data?

Admittedly it is perhaps redundant with the "Loading data" popup, but redundancy is sometimes ok :)

**Comment by floryst** [comment]
Updated:
- show loading on URL datasets

My preference is to not show the loading data screen for sample datasets since we already have an indicator within proximity to the user click action. It's not a strong preference, but one that I think makes sense.

**Review by aylward — APPROVED** [review]
LGTM

**Review by PaulHax — APPROVED** [review]
Slick!

**Pull request merged**
