### PR TITLE
fix(dataset-dicom): throw error if passed file but no volume results

### LINKED ISSUE #478: No image or no error on import of this DICOM file
When loading this DICOM file
[3.000000-NA-78236.zip](https://github.com/Kitware/VolView/files/13254101/3.000000-NA-78236.zip)

No image show up in data browser and green "Dataset loaded" toast showed up.  Expected seeing a loaded image or a error notification.

2 tasks:
- Show error if loading DICOM file, but VolView loads nothing
- See if we can load this file easly

### Approach

File does not load because `dicomIO.categorizeFiles` returns empty list.

### PR DESCRIPTION
**Pull request by PaulHax**
Closes #478

### CODE REVIEW

**Comment by aylward** [comment]
I tried dragging and dropping a .stl file, and it doesn't crash.  It reports data loaded and indicates success, but it doesn't report an error and no volume appears.

I'm using a .stl file from the Challenging Data directory.

**Comment by aylward** [comment]
@floryst - can you try this with the URL provided in https://github.com/Kitware/VolView/issues/475

**Comment by PaulHax** [comment]
Added a warning if loading a file that results in a PolyData, like .stl, and have not loaded an image yet.

**Comment by floryst** [comment]
LGTM!

**Pull request merged**
