### PR TITLE
fix(ruler): change case of call to getOpenGLRenderWindow

### PR DESCRIPTION
**Pull request by PaulHax**
PR for vtk.js
https://github.com/Kitware/vtk-js/pull/2713

### CODE REVIEW

**Comment by floryst** [comment]
LGTM. I will wait for the vtk.js upgrade.

**Comment by floryst** [comment]
FYI vtk.js has been updated to include this change.

**Comment by PaulHax** [comment]
Updating patch file, grrr.   I'll open a PR in vkt.js for the other typescript fixes in the patch.

**Comment by floryst** [comment]
LGTM!

**Pull request merged**
