### PR TITLE
refactor: file loading

### PR DESCRIPTION
**Pull request by floryst**
- Pipeline now supports passing extra context.
- Pipeline processing elements are split out into individual files.
- State file handling is now a pipeline element.
- Extra pipeline elements added for state file handling.
- `datasetStore.loadFiles` is now `importFiles` as a standalone import.
- Result handling uses PipelineResult instead of LoadResult.
- Nicer error messages when loading fails.

### CODE REVIEW

**Comment by PaulHax** [comment]
Whenever you'ed like, I can exercise this PR with the tricky "remote back-end" integration features and we get this merged?

**Comment by floryst** [comment]
Sure! I think this is ready for testing.

**Comment by floryst** [comment]
Resolved the conflict with dicom-web-store.ts.

**Comment by PaulHax** [comment]
Sadly my convoluted integration architecture produced this issue:
1. Load a remote zip-in-zip: `http://localhost:8081/?names=[foo.zip]&urls=[http://localhost:8889/zip-in-zip.zip]`
2. Save a session file
3. Load the session file remotely: `http://localhost:8081/?names=[foo.zip]&urls=[http://localhost:8889/session.volview.zip]`
4. Error loading the file
```
Error: Failed to find archive member /1.3.6.1.4.1.14519.5.2.1.7777.9002.276979399257180200489703215689.2551251219860422.1D000000S0D000000S0D000000S0D000000S1D000000S0D000000.dcm
    at extractArchiveTarget (extractArchiveTarget.ts:42:13)
    at async invokeHandler (pipeline.ts:212:20)
    at async Pipeline.startExecutionContext (pipeline.ts:238:7)
    at async restoreStateFile.ts:100:26
    at async Promise.all (:8081/index 0)
    at async restoreStateFile.ts:98:28
 ```

**Comment by floryst** [comment]
Thanks for catching that! I forgot to add non-archive network resource resolution.

**Comment by PaulHax** [comment]
Better, closer 😅

When there is more than one slice in the dataset and run the remote->session.zip->remote-load-session.zip dance above: Its squaring the number of slices after loading the session.zip file 🤣

[prostate.zip](https://github.com/Kitware/VolView/files/11499519/prostate.zip)

[session.volview.zip](https://github.com/Kitware/VolView/files/11499521/session.volview.zip)

**Comment by floryst** [comment]
Updates: migrated to saving serialized DataSources into the state file for full dataset provenance. This fixes issues regarding nested zip files.

**Review by PaulHax — APPROVED** [review]
You better get a metal for this.  Thank you for fixing my `DatasetFile` mess.  

Can't break it... Except for deserialzing label maps, no file is found.  Adding a slash between archivePath and file.name fixes it:
https://github.com/Kitware/VolView/blob/b1265497ccdecea8441b8de63e528b8c1c0ae6a1/src/store/datasets-labelmaps.ts#L116

**Comment by floryst** [comment]
I pushed a fix for the labelmaps. Once that works on your side and nothing else seems amiss, I'll merge.

**Comment by PaulHax** [comment]
Labelmap fix works.

**Pull request merged**
